name: Markdown Lint

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.md'
      - '.github/workflows/markdown-lint.yaml'
      - '.mdlrc'
      - '.mdl_styl.rb'

permissions:
  contents: read
  packages: read
  statuses: write
  checks: write

jobs:
  mdlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'

      - name: Install mdl
        run: gem install mdl

      - name: Run Markdown Lint
        run: |
          any_check_failed=0
          while IFS= read -r file; do
            echo "Checking: $file"
            if mdl "$file"; then
              echo "Check passed."
            else
              echo "Detected non-zero exit for mdl for $file. Setting mdlint runner to failed."
              any_check_failed=1
            fi
          done < <(find . -type f -name "*.md")
          echo "Markdown Lint run complete"
          exit $any_check_failed