name: ShellCheck

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.sh'
      - '.github/workflows/shellcheck.yaml'
      - '.shellcheckrc'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.sh'
      - '.github/workflows/shellcheck.yaml'
      - '.shellcheckrc'

permissions:
  contents: read
  packages: read
  statuses: write
  checks: write

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: |
          pwd
          any_check_failed=0
          while IFS= read -r script; do
            echo "Checking: $script"
            if shellcheck "$script"; then
              echo "Check passed."
            else
              echo "Detected non-zero exit for shellcheck for $script. Setting shellcheck runner to failed."
              any_check_failed=1
            fi
          done < <(find . -type f -name "*.sh")
          echo "ShellCheck run complete"
          exit $any_check_failed
